version: '3'
services:
  poc_rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" 
      - "15672:15672" 
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq 
    env_file:
      - .env
